<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Arms Properties properties -->
  <xacro:property name="arm_x_size" value="0.05"/>
  <xacro:property name="arm_y_size" value="0.05"/>
  <xacro:property name="arm_z_size" value="0.8"/>
  <xacro:property name="armMass" value="0.001"/>
  <xacro:property name="armOffsetX" value="0.3"/>
  <xacro:property name="armOffsetY" value="0.2"/>
  <xacro:property name="armOffsetZ" value="0.128"/>
	
	
  <!-- Arms Shovel properties -->
  <xacro:property name="shovel_x_size" value="0.4"/>
  <xacro:property name="shovel_y_size" value="0.4"/>
  <xacro:property name="shovel_z_size" value="0.01"/>
  <xacro:property name="shovelMass" value="0.001"/>
  <xacro:property name="shovelOffsetX" value="0.0"/>
  <xacro:property name="shovelOffsetY" value="0.0"/>  
  <xacro:property name="shovelOffsetZ" value="0.0"/>



  <xacro:macro name="arm" params="lr tY">

    
    <link name="${lr}_arm">
      <collision>
        <origin xyz="0 0 ${arm_z_size/2.0}" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${arm_x_size} ${arm_y_size} ${arm_z_size}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${arm_z_size/2.0}" 
        		rpy="0 0 0" />
        <geometry>
          <box size="${arm_x_size} ${arm_y_size} ${arm_z_size}"/>
        </geometry>
        <material name="green"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${arm_z_size/2.0}" 
        		rpy="0 0 0" />
        <mass value="${armMass}"/>
        <box_inertia 
          m="${armMass}" 
          x="${arm_x_size}" 
          y="${arm_y_size}"
          z="${arm_z_size}"/>

            <inertia 
                ixx="0.1" ixy="0" ixz = "0"
                          iyy = "0.1" iyz = "0"
                                      izz = "0.1"

            />
      </inertial>
    </link>

    <gazebo reference="${lr}_arm">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />
      <kd>10000000.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
      <material>Gazebo/Green</material>
    </gazebo>


    <joint name="${lr}_arm_hinge" type="continuous">
      <parent link="chassis"/>
      <child link="${lr}_arm"/>
      <origin 
        xyz = "${armOffsetX} ${-tY*(armOffsetY+arm_x_size)} 0.0" 
        rpy = "0 0 0" /> 
      <axis xyz="0 1 0" 
      		  rpy="0 0 0" />
      <limit effort="10000.0" velocity="0.5"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>
    
    <transmission name="${lr}_arm_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_arm_hinge">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${lr}ArmMotor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    
    <!-- SHOVEL -->
    <link name="${lr}_arm_shovel">
      <collision>
        <origin xyz="0 0 0" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${shovel_x_size} ${shovel_y_size} ${shovel_z_size}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" 
        		rpy="0 0 0" />
        <geometry>
          <box size="${shovel_x_size} ${shovel_y_size} ${shovel_z_size}"/>
        </geometry>
        <material name="green"/>
      </visual>
      
      <collision>
        <origin xyz="0 ${tY*(shovel_x_size/2)} ${shovel_x_size/2}" 
        		rpy="1.57 0 0" />
        <geometry>
            <box size="${shovel_x_size} ${shovel_y_size} ${shovel_z_size}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 ${tY*(shovel_x_size/2)} ${shovel_x_size/2}" 
        		rpy="1.57 0 0" />
        <geometry>
          <box size="${shovel_x_size} ${shovel_y_size} ${shovel_z_size}"/>
        </geometry>
        <material name="green"/>
      </visual>
      
      
      <collision>
        <origin xyz="0 ${-tY*(shovel_x_size/2)} ${shovel_x_size/2}" 
        		rpy="1.57 0 0" />
        <geometry>
            <box size="${shovel_x_size} ${shovel_y_size} ${shovel_z_size}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 ${-tY*(shovel_x_size/2)} ${shovel_x_size/2}" 
        		rpy="1.57 0 0" />
        <geometry>
          <box size="${shovel_x_size} ${shovel_y_size} ${shovel_z_size}"/>
        </geometry>
        <material name="green"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" 
        		rpy="0 0 0" />
        <mass value="${shovelMass}"/>
        <box_inertia 
          m="${shovelMass}" 
          x="${shovel_x_size}" 
          y="${shovel_y_size}"
          z="${shovel_z_size}"/>
            <inertia 
                ixx="0.1" ixy="0" ixz = "0"
                          iyy = "0.1" iyz = "0"
                                      izz = "0.1"

            />
      </inertial>
    </link>

    <gazebo reference="${lr}_arm_shovel">
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
      <kp  value="10000000.0" />
      <kd>10000000.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
      <material>Gazebo/Blue</material>
    </gazebo>


    <joint name="${lr}_arm_shovel_hinge" type="fixed">
      <parent link="${lr}_arm"/>
      <child link="${lr}_arm_shovel"/>
      <origin 
        xyz = "${shovelOffsetX} ${shovelOffsetY} ${arm_z_size}" 
        rpy = "${-tY*1.57} 0 0" />
    </joint>
    
    
    <link name="${lr}_arm_shovel_lid">
      
      <collision>
        <origin xyz="0 0 ${shovel_x_size/2}" 
        		rpy="0 1.57 0" />
        <geometry>
            <box size="${shovel_x_size} ${shovel_y_size} ${shovel_z_size/5}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${shovel_x_size/2}" 
        		rpy="0 1.57 0" />
        <geometry>
          <box size="${shovel_x_size} ${shovel_y_size} ${shovel_z_size/5}"/>
        </geometry>
        <material name="red"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${shovel_x_size/2}" 
        		rpy="0 1.57 0" />
        <mass value="${shovelMass}"/>
        <box_inertia 
          m="${shovelMass}" 
          x="${shovel_x_size}" 
          y="${shovel_y_size}"
          z="${shovel_z_size/5}"/>
            <inertia 
                ixx="0.1" ixy="0" ixz = "0"
                          iyy = "0.1" iyz = "0"
                                      izz = "0.1"

            />
      </inertial>
    </link>
    
    <gazebo reference="${lr}_arm_shovel_lid">
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
      <kp  value="10000000.0" />
      <kd>10000000.0</kd>
      <!--<minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
      -->
      <material>Gazebo/Red</material>
    </gazebo>
    
    <joint name="${lr}_arm_shovel_lid_joint" type="prismatic">
      <origin rpy="${-tY*1.57} 0 0" xyz="${shovel_x_size/2} 0 ${arm_z_size}" />
      <parent link="${lr}_arm" />
      <child link="${lr}_arm_shovel_lid" />
      <axis xyz="0 0 1" />
      <limit effort="1000.0" lower="-1.0" upper="0.0" velocity="1.0" />
    </joint>
  
  
  <transmission name="${lr}_arm_shovel_lid_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_arm_shovel_lid_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${lr}ArmShovelLidMotor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    
  </xacro:macro>

</robot>
