<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Arms Properties properties -->
  <xacro:property name="box_width" value="0.6"/>
  <xacro:property name="box_length" value="0.45"/>
  <xacro:property name="box_height" value="0.4"/>
  <xacro:property name="box_side_width" value="0.01"/>

  <xacro:macro name="ball_container">




    <link name = "box">
       <!-- base -->
       <collision name="base_collision">
        <origin xyz="0 0 0" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${box_length} ${box_width} ${box_side_width}"/>
        </geometry>
      </collision>

      <visual name="base_visual">
        <origin xyz="0 0 0" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${box_length} ${box_width} ${box_side_width}"/>
        </geometry>
        <material name="white"/>
      </visual>

       <!-- left side -->
       <collision name="left_collision">
        <origin xyz="0 ${box_width / 2} ${box_height / 2}" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${box_length} ${box_side_width} ${box_height}"/>
        </geometry>
      </collision>

      <visual name="left_visual">
        <origin xyz="0 ${box_width / 2} ${box_height / 2}" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${box_length} ${box_side_width} ${box_height}"/>
        </geometry>
        <material name="white"/>
      </visual>

       <!-- right side -->
       <collision name="right_collision">
        <origin xyz="0 ${- box_width / 2} ${box_height / 2}" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${box_length} ${box_side_width} ${box_height}"/>
        </geometry>
      </collision>

      <visual name="right_visual">
        <origin xyz="0 ${- box_width / 2} ${box_height / 2}" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${box_length} ${box_side_width} ${box_height}"/>
        </geometry>
        <material name="white"/>
      </visual>

       <!-- front side -->
       <collision name="front_collision">
        <origin xyz="${box_length / 2} 0 ${box_height / 2}" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${box_side_width} ${box_width} ${box_height}"/>
        </geometry>
      </collision>

      <visual name="front_visual">
        <origin xyz="${box_length / 2} 0 ${box_height / 2}" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${box_side_width} ${box_width} ${box_height}"/>
        </geometry>
        <material name="white"/>
      </visual>

       <!-- back side -->
       <collision name="back_collision">
        <origin xyz="${-box_length / 2} 0 ${box_height / 2}" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${box_side_width} ${box_width} ${box_height}"/>
        </geometry>
      </collision>

      <visual name="back_visual">
        <origin xyz="${-box_length / 2} 0 ${box_height / 2}" 
        		rpy="0 0 0" />
        <geometry>
            <box size="${box_side_width} ${box_width} ${box_height}"/>
        </geometry>
        <material name="white"/>
      </visual>


      <inertial>
            <mass value="0.01"/>
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
            <inertia 
                ixx="0.1" ixy="0" ixz = "0"
                          iyy = "0.1" iyz = "0"
                                      izz = "0.1"

            />


      </inertial>

    </link>

    <gazebo reference="box">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="container_joint" type="fixed">
      <parent link="chassis"/>
      <child link="box"/>
      <origin 
        xyz = "${- box_length / 2} 0.0 0.05" 
        rpy = "0 0 0" /> 
      <axis xyz="0 1 0" 
      		  rpy="0 0 0" />
    </joint>

  </xacro:macro>
</robot>
